### PR TITLE
upgrade font-awesome to 4.3.0

### PR DESCRIPTION
**Pull request by PrplHaz4**
previous font-awesome update (bf881dff2fdad739cb4e4c6e357faf99ee345b53) did not include updating packages.php and links to cdn

### CODE REVIEW

**Comment by PrplHaz4** [comment]
@hijarian any chance of getting this included soon?

**Comment by PrplHaz4** [comment]
@amrbedair since you updated bootstrap, this might go with it nicely :)

Also, it doesn't look like the update to bootstrap 3.3.2 included the cdn config in packages.php

**Comment by amrbedair** [comment]
@PrplHaz4  will check the cdn soon

**Comment by PrplHaz4** [comment]
Thanks @amrbedair!! :+1:

**Pull request merged**
